import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdirSync, writeFileSync, rmSync, symlinkSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join, resolve } from 'node:path'
import { validarCampaignConfig, fusionarConfig, validarTriggers, normalizarTrigger } from '../src/config/campaign-schema.js'
import { validarDatos } from '../src/config/seed-datos.js'
import { getImagen } from '../src/lib/assets.js'
import { revisarPrecios } from '../src/brain/agent-brain.js'
import { flattenFactSheet } from '../src/response/factsheet-loader.js'
import { construirSystemPrompt } from '../src/brain/verticals/colageno.js'
import { normalizeText } from '../src/webhook/campaign-resolver.js'
import { getCampaigns, createCampaign, updateCampaign, activarCampaign } from '../src/routes/campaigns.js'
import { getAgentConfigV2, saveAgentConfigV2 } from '../src/api/flow.js'
import { canalDeTenant, datosComercialesPorLead, plantillasDe, politicaEnvio } from '../src/motor/followupEngine.js'
import { textoDePlantilla } from '../src/whatsapp/cloud/plantillas-catalogo.js'
const cfg=()=>({vertical:'tienda',agente:{nombre:'Asesor de prueba',empresa:'Empresa de prueba',nombreProducto:'Producto X'},factSheet:{precio:{textoExacto:'S/139',monto:139,moneda:'S/'}}})
const reply=()=>({statusCode:200,body:null,code(n){this.statusCode=n;return this},send(v){this.body=v;return v}})
const req=body=>({user:{tenantId:'tenant_test',role:'ADMIN'},params:{id:'1'},body})
const store=()=>{let row={id:1,tenantId:'tenant_test',version:1,activa:true,config:cfg()};return {campaign:{async findFirst({where}){return where.tenantId===row.tenantId?structuredClone(row):null},async update({where,data}){assert.equal(where.tenantId,row.tenantId);if(where.version!==row.version)throw Object.assign(new Error('conflicto'),{code:'P2025'});row={...row,...data,version:row.version+1};return structuredClone(row)}},get row(){return row}}}

test('100 montos parciales nunca se validan como el precio completo',()=>{
 for(let n=10;n<110;n++){const c=cfg();c.factSheet.precio={textoExacto:'S/'+n+'9',monto:n};assert.equal(validarCampaignConfig(c).ok,false);assert.deepEqual(revisarPrecios('S/'+n,{precioTexto:'S/'+n+'9',precioMonto:n}).malos,['S/'+n])}
})
for(const [texto,monto] of [['S/. 139',139],['S/ 124.50',124.5],['S/ 1,500',1500],['124,50 soles',124.5],['USD 139',139]])test('precio exacto '+texto,()=>{const c=cfg();c.factSheet.precio={textoExacto:texto,monto};assert.equal(validarCampaignConfig(c).ok,true)})
test('uso 139 y cantidad 3 no son precios',()=>{const c=cfg();c.factSheet.precio={textoExacto:'uso 139',monto:139};assert.equal(validarCampaignConfig(c).ok,false);assert.deepEqual(revisarPrecios('S/3',{precioTexto:'3 envases: S/139'}).malos,['S/3'])})
for(const peligro of ['__proto__','constructor','prototype'])test('rechaza clave peligrosa '+peligro,()=>{const p=JSON.parse('{"factSheet":{"'+peligro+'":{"agente":{"nombre":"X","empresa":"Y"}}}}');assert.throws(()=>fusionarConfig(cfg(),p));assert.equal(validarCampaignConfig(p).ok,false);assert.equal({}.agente,undefined)})
test('identidad heredada no pasa el contrato',()=>{const p=Object.create({agente:cfg().agente});p.factSheet={};assert.equal(validarCampaignConfig(p).ok,false)})
test('merge de precio parcial conserva monto y moneda',()=>{const c=fusionarConfig(cfg(),{factSheet:{precio:{textoExacto:'S/ 139'}}});assert.equal(c.factSheet.precio.monto,139);assert.equal(c.factSheet.precio.moneda,'S/');assert.equal(validarCampaignConfig(c).ok,true)})
test('trigger pack-3 coincide en escritura, resolver y prueba',()=>{assert.equal(normalizarTrigger('Páck-3'),'pack3');assert.equal(normalizeText('Páck-3'),'pack3');assert.equal(validarTriggers([]).ok,false);assert.equal(validarTriggers([],{permitirVacios:true}).ok,true)})
for(const archivo of ['../package.json','/etc/passwd','C:/secret.png','tenant_other/precios.png'])test('rechaza imagen '+archivo,()=>{const c=cfg();c.factSheet.imagenes={precios:{archivo,mimetype:'image/png'}};assert.equal(validarCampaignConfig(c,{tenantId:'tenant_test'}).ok,false);assert.equal(getImagen('precios','tenant_test',c.factSheet.imagenes),null)})
test('no sirve imagen legacy de otro tenant ni storage remoto sin implementación',()=>{assert.equal(getImagen('precios','tenant_test',{precios:{archivo:'precios-bioayur.png'}}),null);const c=cfg();c.factSheet.imagenes={precios:{storageKey:'private/key'}};assert.equal(validarCampaignConfig(c,{tenantId:'tenant_test'}).ok,false)})
test('firma de imagen, fallo transitorio y symlink fuera de assets',()=>{
 const base=fileURLToPath(new URL('../assets/',import.meta.url)),dir=resolve(base,'tenant_test');assert.ok(dir.startsWith(resolve(base)+join('/').replaceAll('/','\\')) || dir.startsWith(resolve(base)+'/'))
 mkdirSync(dir,{recursive:true});const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2fAAAAABJRU5ErkJggg==','base64');const def={precios:{archivo:'tenant_test/imagen.png',mimetype:'image/png'}}
 try{assert.equal(getImagen('precios','tenant_test',def),null);writeFileSync(join(dir,'imagen.png'),png);assert.ok(getImagen('precios','tenant_test',def));writeFileSync(join(dir,'imagen.png'),'not an image');assert.equal(getImagen('precios','tenant_test',def),null);symlinkSync(fileURLToPath(new URL('../data/',import.meta.url)),join(dir,'escape'),'junction');assert.equal(getImagen('precios','tenant_test',{precios:{archivo:'tenant_test/escape/sitio-publico.json'}}),null)}finally{rmSync(dir,{recursive:true,force:true})}
})
test('producto diferente no hereda fórmula, dosis, sabor ni envío del cliente anterior',()=>{const c=cfg();c.vertical='colageno';c.factSheet={propuestaValor:'Producto de un ingrediente, información por confirmar'};const p=construirSystemPrompt({campaignConfig:c,fs:flattenFactSheet(c),vendorNombre:'Asesor',estadoLead:{}});assert.doesNotMatch(p,/300g|15g|stevia|frutos rojos|resveratrol|P2908325N|5 activos/);assert.match(p,/únicamente según ficha/);assert.match(p,/PEDIDO CONFIRMADO = ESCALAR/)})
test('alta activa sin ficha se rechaza y borrador explícito se permite',async()=>{const db={vendor:{findFirst:async()=>({id:2})},campaign:{create:async({data})=>data}};let rep=reply();await createCampaign(req({slug:'X',nombre:'X',vendorId:2,triggers:['xx']}),rep,db);assert.equal(rep.statusCode,400);rep=reply();await createCampaign(req({slug:'X',nombre:'X',vendorId:2,activa:false}),rep,db);assert.equal(rep.statusCode,201);assert.equal(rep.body.activa,false)})
test('campaña default con descubrimiento permite triggers vacíos',async()=>{const c=cfg();c.atribucion={esCampanaDefault:true,mensajeDescubrimiento:'¿Qué producto te interesa?'};const rep=reply();await createCampaign(req({slug:'X',nombre:'X',vendorId:2,config:c}),rep,{vendor:{findFirst:async()=>({id:2})},campaign:{create:async({data})=>data}});assert.equal(rep.statusCode,201)})
test('borrar una sección exige confirmación y una activa no pierde la ficha',async()=>{for(const body of [{config:{factSheet:null}},{config:null},{config:null,force:true}]){const rep=reply();await updateCampaign(req({...body,version:1}),rep,store());assert.ok([400,409].includes(rep.statusCode))}})
test('dos cambios simultáneos conservan uno y devuelven 409 al otro',async()=>{const db=store(),a=reply(),b=reply();await Promise.all([updateCampaign(req({version:1,config:{agente:{nombre:'Nombre nuevo'}}}),a,db),updateCampaign(req({version:1,config:{factSheet:{precio:{textoExacto:'S/149',monto:149}}}}),b,db)]);assert.equal([a.statusCode,b.statusCode].filter(n=>n===409).length,1);assert.equal(db.row.version,2);assert.equal(db.row.config.agente.nombre,'Nombre nuevo')})
test('editor exige versión, preserva secciones y bloquea un borrador obsoleto',async()=>{const db=store();let rep=reply();await getAgentConfigV2({...req({}),query:{campaignId:1}},rep,db);assert.equal(rep.body.version,1);rep=reply();await saveAgentConfigV2(req({campaignId:1,factSheet:{propuestaValor:'nuevo'}}),rep,db);assert.equal(rep.statusCode,428);rep=reply();await saveAgentConfigV2(req({campaignId:1,version:1,factSheet:{propuestaValor:'nuevo'}}),rep,db);assert.equal(rep.statusCode,200);assert.equal(db.row.config.factSheet.precio.monto,139);rep=reply();await saveAgentConfigV2(req({campaignId:1,version:1,agente:{nombre:'antiguo'}}),rep,db);assert.equal(rep.statusCode,409)})
test('campaña sin ficha no se activa',async()=>{const rep=reply();await activarCampaign(req({}),rep,{campaign:{findFirst:async()=>({id:1,config:null})}});assert.equal(rep.statusCode,400)})
test('seguimientos usan el vertical de campaña y descartan asociaciones entre tenants',async()=>{const db={lead:{findMany:async()=>[{id:1,tenantId:'tenant_test',campaign:{tenantId:'tenant_test',nombre:'Curso',config:{vertical:'colageno',agente:{nombreProducto:'Producto X'}}}},{id:2,tenantId:'tenant_other',campaign:{tenantId:'tenant_test',config:cfg()}}]}};const m=await datosComercialesPorLead([1,2],db);assert.equal(m.get(1).vertical,'colageno');assert.equal(m.get(1).producto,'Producto X');assert.equal(m.has(2),false);assert.doesNotMatch(plantillasDe('tenant_test','colageno').followup_24h,/pagas al recibir|promo|gratis/)})
test('sin canal propio no utiliza instancia global',async()=>{const c=await canalDeTenant('tenant_test',new Map(),async()=>null);assert.equal(c.canal,null);assert.equal(c.instancia,null)})
test('canal resuelto de otro tenant se descarta',async()=>{assert.equal((await canalDeTenant('tenant_test',new Map(),async()=>({tenantId:'otro',provider:'evolution',externalKey:'otra-instancia'}))).canal,null)})
test('plantilla e idioma del canal mandan, un nombre desconocido no inventa el texto',()=>{const p=politicaEnvio('cloud','followup_24h',{CLOUD_TEMPLATE_FOLLOWUP_24H:'global'},{credenciales:{templates:{followup_24h:{nombre:'propia',idioma:'es_PE',cuerpo:'Hola {{1}}, sobre {{2}}'}}}});assert.equal(p.plantilla,'propia');assert.equal(p.idioma,'es_PE');assert.equal(textoDePlantilla('followup_24h',['A','X'],p),'Hola A, sobre X');assert.match(textoDePlantilla('followup_24h',['A','X'],{plantilla:'desconocida'}),/Plantilla desconocida/);assert.doesNotMatch(textoDePlantilla('followup_24h',[],{plantilla:'desconocida'}),/gratis|recibir/)})
test('seed rechaza nulos, tipo de triggers falso, rol y ficha ausente',()=>{for(const d of [{vendors:[null],campaigns:[null]},{tenant:{tenantId:'test',displayName:'Test'},vendors:[{nombre:'X',telefono:'51999999999',role:'ROOT'}],campaigns:[{slug:'X',nombre:'X',vendorTelefono:'51999999999',triggers:{length:0}}]}])assert.ok(validarDatos(d).length)})
test('módulos de arranque y seguimiento resuelven todas sus importaciones',async()=>{assert.equal(typeof (await import('../src/webhook/handler.js')).handleWebhook,'function');assert.equal(typeof (await import('../src/motor/followupEngine.js')).ejecutarFollowups,'function')})

test('campañas: sin tenant autenticado no usa el tenant activo',async()=>{await assert.rejects(()=>getCampaigns({user:{}},reply(),{campaign:{findMany:async()=>assert.fail('No consultar sin tenant')}}),e=>e.statusCode===403)})
test('campañas: una edición comercial sin versión exige recargar',async()=>{const rep=reply();await updateCampaign(req({config:{agente:{nombre:'nuevo'}}}),rep,store());assert.equal(rep.statusCode,428)})

test('imagen omitida por la campaña no hereda su foto legacy',()=>assert.equal(getImagen('precios','bioayur',{}),null))

test('editor no borra el precio con null sin confirmación',async()=>{const rep=reply();await saveAgentConfigV2(req({campaignId:1,version:1,factSheet:{precio:null}}),rep,store());assert.equal(rep.statusCode,409)})
test('un null que ya existía no exige confirmación de borrado',async()=>{const db=store();db.row.config.factSheet.ofertaHoy=null;const rep=reply();await saveAgentConfigV2(req({campaignId:1,version:1,factSheet:{ofertaHoy:null,propuestaValor:'actualizada'}}),rep,db);assert.equal(rep.statusCode,200)})
